name: itmm_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_svg: ^0.17.4


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/UNN1.jpg
    - assets/google_fonts/
    - assets/login.png
    - assets/LogoUNN.png
    - assets/Lock.png
    - assets/LightCircle.png
    - assets/BlueCircle.png
    - assets/LightBlue.png
    - assets/LoginUNN.png
    - assets/Pass.png